# Identificación del proyecto en SonarCloud
sonar.projectKey=FabianCastillo12_prueba-usuarios
sonar.organization=fabiancastillo12
sonar.host.url=https://sonarcloud.io

# Archivos de test (distribuidos por el proyecto)
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts

# Ignorar archivos generados
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

# Incluir coverage (Jest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
